"""Initial migration - create job_pages_raw table

Revision ID: 001
Revises: 
Create Date: 2025-08-29 18:12:45.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_pages_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_html', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_job_pages_raw_id'), 'job_pages_raw', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_pages_raw_id'), table_name='job_pages_raw')
    op.drop_table('job_pages_raw')
    # ### end Alembic commands ###
