"""Added Models

Revision ID: 7e2a7bd5583c
Revises: 
Create Date: 2025-09-04 17:24:03.800976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2a7bd5583c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_pages_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_html', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_job_pages_raw_id'), 'job_pages_raw', ['id'], unique=False)
    op.create_table('job_pages_parsed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_page_raw_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date_posted', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_page_raw_id'], ['job_pages_raw.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_page_raw_id')
    )
    op.create_index(op.f('ix_job_pages_parsed_id'), 'job_pages_parsed', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_pages_parsed_id'), table_name='job_pages_parsed')
    op.drop_table('job_pages_parsed')
    op.drop_index(op.f('ix_job_pages_raw_id'), table_name='job_pages_raw')
    op.drop_table('job_pages_raw')
    # ### end Alembic commands ###
